name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - 
         name: Checkout
         uses: actions/checkout@v2
      - 
         name: Login to Docker Hub
         uses: docker/login-action@v1
         with:
           username: "chalut"
           password: "Chalut002."
      -
         name: docker build
         run: docker build . --file Dockerfile --tag chalut/blackjack
      -
         name: Docker push
         run: docker push chalut/blackjack
      -   
         name: 'Noti JOM'
         uses: snow-actions/line-notify@v1.0.0
         with:
             access_token: OoeNUGioVM5rzvnDQvXOpOIqqVD2vUkpxRyGeeRIZAF
             message: blackjack PUSH to dockerhub complete.!!!
